server:
      port: 9197

spring:
     application:
             name: CONFIG-SERVICE
     cloud: 
       config:
           server:
              git:
                uri: https://github.com/amrjais/cloud-config-server.git
       enabled: true
eureka:
      client:
           register-with-eureka: true
           fetch-registry: true
           serviceUrl:
               defaultZone: http://localhost:8762/eureka/
      instance:
          hostname: localhost
             
    