server:
      port: 8989

spring:
     application:
             name: CLOUD-GATEWAY
     cloud:
         gateway:
             routes:
                 - id: order-service
                   uri: lb://ORDER-SERVICE
                   predicates: 
                         - Path= /order/**
                   filters:
                     - name: CircuitBreaker
                       args:
                          name : order-service
                          fallbackuri: forward:/orderFallBack

                 - id: payment-service
                   uri: lb://PAYMENT-SERVICE
                   predicates: 
                         - Path= /payment/**
                   filters:
                    - name: CircuitBreaker
                      args:
                          name : payment-service
                          fallbackuri: forward:/paymentFallBack
         #config:
          #  uri:
           #   - http:localhost:9196
#eureka:
 #     client:
  #         register-with-eureka: true
   #        fetch-registry: true
    #       service-url: 
     #          default-zone: http://localhost:8761/eureka/
      #instance:
       #   hostname: localhost

management:
  endpoints: 
    web:
     exposure:
      include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
       isolation:
         thread:
           timeoutInMilliseconds: 5000

  
 
             