server:
      port: 9192

spring:
     datasource:
             url: jdbc:h2:mem:testdb2 
             driverClassName: org.h2.Driver
     h2:
      console:
             enabled: true 
     application:
             name: ORDER-SERVICE


     cloud:
      config:
        uri:
          - http:localhost:9196